### ISSUE TITLE
Problem cloning repo due to naming of files - "invalid path '#include <stdio.h>"

### ISSUE THREAD

**Issue by FireFoxHD** [manish-virgat/Hacktoberfest-C-Program#73]
Due to the naming of some of the folders in the repo the is an issue when attempting to clone the repository as seen in the error below : 

error: invalid path '#include <stdio.h>/Name - Neeraj Singh/reg No - 12012889/Vowelchecker.c'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by manish-virgat** [comment]
Solved
